source /Data/greenplum_load/gp_binaries/gpload/greenplum_path.sh

psql -h 10.40.0.151 -p 5544 -d fgdwprd -U gpadmin -c "
SET DATESTYLE TO ISO,DMY;

INSERT INTO STGDB.TMP_CASHMEMOS
(ACCCENTRENO,TRNNO, DOCNO, DOCDATE, TERMINALID, USERSID, CLPNO, ENDTIMESTAMP, CMTYPE,
STARTTIMESTAMP, NETAMT, NOOFREPRINTS, REPRINTDATE, REPRINTREASON, REPRINTTIME, ROUNDINGFIGURE,
UPDATIONAUTHORISEDBY, VVIPCARDNO, MEMBERSHIPNO, CANCELLATIONDATE, CANCELLATIONTIME,
VATINVOICENO, EMPCODE, REDEMPTIONAMT, KIDSCARDNO, KIDSREDEMPTIONAMT, MEMBERCARDNO,
EDCBALANCEAMT, MEMBERREDEMPTIONAMT, MEMBERBALANCEAMT, SERIALNO)
SELECT
COALESCE(ACCCENTRENO, -9), COALESCE(TRNNO, -9), DOCNO, DOCDATE, TERMINALID, USERSID, CLPNO, ENDTIMESTAMP, CMTYPE,
STARTTIMESTAMP, NETAMT, NOOFREPRINTS, REPRINTDATE, REPRINTREASON, REPRINTTIME, ROUNDINGFIGURE,
UPDATIONAUTHORISEDBY, VVIPCARDNO, MEMBERSHIPNO, CANCELLATIONDATE, CANCELLATIONTIME,
VATINVOICENO, EMPCODE, REDEMPTIONAMT, KIDSCARDNO, KIDSREDEMPTIONAMT, MEMBERCARDNO,
EDCBALANCEAMT, MEMBERREDEMPTIONAMT, MEMBERBALANCEAMT, SERIALNO
FROM EXTDB.EXT_CASHMEMOS_BAD;

INSERT INTO EDWDB.EDW_DATA_LOAD_LOG
(Load_Type, Load_Date, Load_Time, Table_Name, Loaded_Recs, Error_Records, User_Name)
SELECT 'I', CURRENT_DATE, TO_CHAR(NOW(), 'HH:MI:SS'), 'CASHMEMOS - TMP',
(select cast(count(*) as numeric) from STGDB.TMP_CASHMEMOS) AS Loaded_Recs,
(select cast(count(*) as numeric) from ERRDB.ERR_CASHMEMOS) AS Error_Records,
user;"

